### ISSUE TITLE
Demo v2 To-Do

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DouglasDataCapturePlatform#152]
# Demo v2 To-Do

Deliverable is a DEMO that is usable by multiple users (and user types) so that Clinicians can examine their individual use cases

## Bugs
- [x] Remove 'the' from the form
- [x] add some metadata to export file name -  date, user
- [x] investigate negative values for demo measures

## Step 1: Form Instrument Design
- [x] Consistent validation on frontend and backend, implemented using AJV
- [x] Stabilize the instrument schemas
  - [x] Include tags (e.g., demographics, cognitive, etc.)
- [x] Provide a complete design language for instruments
  - [x] Dividers (i.e., sections that will be rendered on the UI)
  - [x] Different input types
    - [x] Sliders for likert scale
    - [x] Drop-down with limited choices 
    - [x] Date
    - [x] Short Box
    - [x] Long box
    - [x] Radio box
    - [x] Checkbox
  - [x] Finish help design
- [x] Date instrument collected
- [x] Summary output at end of instrument
  - [x] Use CSS print media target for print mode
- [x] Instrument schema can define derived values
- [x] Version of form render interface
- [x] Add version to the instrument creator
- [x] Fix overlap of active subject and notifications
- [x] Add commit to login screen
- [x] Link to given commit
- [x] Add field in instrument for language
- [x] Linkage between French and English - add in metadata (X-en, X-fr)

## Step 2: Implement Group
- [x] Clinic -> Group

## Step 3: Demographics
- [x] Implement as an instrument
- [x] Decide on mandatory measures
- [x] Investigate best practices for demographics

## Step 4: Subject Lookup
- [ ] Should show demographics
- [x] Possibly generic plotting interface, using computed measures of instruments
  - [ ] Compare result for subject with average in clinic (e.g., this subject is in the Nth percentile for scale X)
- [x] Bring up report page again

## Step 5: Data Export
- [x] CSV export
  - [x] Long data format unless we find something wiz-bang easy
- [x] Coordinate with instrument schema

## Step 6: Implement Useful Forms
- [x] MMSE
- [x] MoCA

## Step 7: Final Cleanup and Refinement
- [x] Add `mailto` form for feedback and new instrument requests
- [x] Add translations for all parts of the UI
- [x] Ensure accessibility on mobile and tablet
