### ISSUE TITLE
Implement subject lookup

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DouglasDataCapturePlatform#154]
# Tasks
- [ ] Should show demographics
- [ ] Possibly generic plotting interface, using computed measures of instruments
- [ ] Bring up report page again
