### ISSUE TITLE
Demo v2 TODO v2

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/DouglasDataCapturePlatform#243]
# Datepicker
- [x] picker should update based on value of input element
- [x] picket should start at 18 years old from today
# Instrument Records
- [x] instead of plotting individual instruments, a single plot field to select form all data
- [x] summary view of any instrument like summary from end of instrument after clicking existing table
# View instrument
- [x] make more interactive, colour/highlight/animate the entry
- [x] make any area clickable, drop "Learn more"
- [x] subject page should use "Next" instead of submit

# Subject form
- [x] clear button
- [x] autofill with active subject

# Active subject
- [x] left on mobile
- [x] right on desktop
- [x] 10s timeout
- [x] bigger buttons
- [x] make clear current subject explicit

# Manage instrument
- [x] allow group manager to hide/show instruments for users of group
- [x] allow group manager to create aggregate instruments for workflow

# Forms in general
- [x] dynamic list search and completion (for tags initially) and removal
- [x] required vs optional fields control
- [x] binary value to be explicit true/false yes/no for form rendering
- [x] multiple select variant of Option list, with typing autocomplete, with OPTIONAL ability to add items

# Demographics
- [ ] basic first-visit demographics form
- [ ] expanded demographics
- [ ] followup/repeat visit demographics

# Completed instrument
- [ ] include subject information for completed instrument
